name: Hugo CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install Hugo
        run: |
          sudo snap install hugo --channel=extended
      - name: Build Site
        run: hugo
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: public
