name: Hugo CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: recursive 
      - name: Install Hugo
        run: |
          sudo snap install hugo --channel=extended
      - name: Build Site
        run: hugo
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: public
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # deploy web app using Azure credentials
      - uses: azure/webapps-deploy@v1
        with:
          app-name: 'navneetg-hugo-web-app-three'
          package: "./public"

      # Azure logout 
      - name: logout
        run: |
          az logout